[[stack]]
name = "3-app"
[stack.config]
server = "test.vulca.run"
poll_for_updates = true
repo = "vulcanet/coolify-test"
clone_path = "/opt/3-app"
webhook_secret = "senhaboa"
file_paths = ["docker-compose.yml"]
